### ISSUE TITLE
Reduce required clicks to create a quote

### ISSUE THREAD

**Issue by Jokler** [Mavulp/quotes#1]
Some ideas for what could be changed:
- [ ] The "Add a block" box is quite large so it could always show all four options instead.
- [ ] Make a highlight checkbox next to each block instead of it being a content type so text blocks can be added without thinking about where the highlight should go.
- [ ] Allow users to create multiple text fragments by automatically splitting on new lines when content is pasted (should be optional)
  - This could also be extended with additional features like extracting the usernames and detecting images automatically.

Feel free to create additional issues for any of these you want to implement.

**Comment by dolanske** [comment]
Resolved number 1 by removing dropdown and made all block buttons available immediately. Number 2 is possible but I want to hear user feedback on creation first. 

I will add number 3 into its own issue as a future idea
